version: '3.1'

services:
  dremio:
      build:
        context: ./dremio
      networks:
          - dremio-network
      ports:
          - "9047:9047"
          - "31010:31010"
          - "45678:45678"
networks:
  dremio-network:
    driver: bridge
      
